export interface GambleEvent {
  id: string;
  label: string;
  description: string;
  amount?: number;
  wipeOut: boolean;
  jackpot: boolean;
}

export const GAMBLE_EVENTS: GambleEvent[] = [
  // ── Dramatic losses (wipe cash to $0) ──────────────────────────────
  {
    id: "gamble_casino",
    label: "Casino Meltdown",
    description: "A wild night at the casino wiped out your entire wallet.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_badinvestment",
    label: "Bad Investment",
    description: "The startup you bet on collapsed overnight. Savings: gone.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_identitytheft",
    label: "Identity Theft",
    description: "Someone cleaned out your account before the bank caught it.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_housefire",
    label: "House Fire",
    description: "Insurance didn't cover it. Every last cent went to repairs.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_cryptocrash",
    label: "Crypto Crash",
    description: "You went all in the night before the bottom fell out.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_pyramidscheme",
    label: "Pyramid Scheme",
    description: "Turns out 'guaranteed returns' were guaranteed nothing.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_divorce",
    label: "Messy Divorce",
    description: "The lawyers took their cut, and then some.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_hacked",
    label: "Bank Account Hacked",
    description: "A phishing email did more damage than you thought possible.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_stolenidentitytax",
    label: "Fraudulent Tax Filing",
    description:
      "Someone filed taxes in your name and pocketed the refund, plus your savings.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_flooded",
    label: "Basement Flood",
    description: "Water damage swallowed every dollar you had put aside.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_lawsuitloss",
    label: "Lost a Lawsuit",
    description: "The judge ruled against you. The damages were brutal.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_ponzicollapse",
    label: "Ponzi Scheme Collapse",
    description: "The fund manager vanished. So did everyone's money.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_carcrash",
    label: "Uninsured Car Crash",
    description: "You forgot to renew the policy. Terrible timing.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_businessfailure",
    label: "Business Went Under",
    description: "You poured everything into it. It closed within the year.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_stockmarketcrash",
    label: "Stock Market Crash",
    description: "Your whole portfolio was in one overheated sector.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_blackmail",
    label: "Blackmail",
    description: "You paid up quietly. It cost you everything.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_venmoscam",
    label: "Peer-to-Peer Scam",
    description: "A fake marketplace buyer drained your linked account.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_gamblingaddiction",
    label: "Bad Betting Streak",
    description: "You kept telling yourself one more hand would fix it.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_embezzled",
    label: "Business Partner Embezzled Funds",
    description: "By the time you noticed the books, it was too late.",
    wipeOut: true,
    jackpot: false,
  },
  {
    id: "gamble_hurricane",
    label: "Hurricane Damage",
    description: "The storm took the roof, the car, and the rainy-day fund.",
    wipeOut: true,
    jackpot: false,
  },

  // ── Dramatic wins (big flat bonus) ─────────────────────────────────
  {
    id: "gamble_jackpot",
    label: "Lottery Jackpot",
    description: "Your numbers hit. All of them.",
    amount: 5000,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_inheritance",
    label: "Surprise Inheritance",
    description: "A distant relative you barely remember left you a fortune.",
    amount: 4000,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_startupsold",
    label: "Startup Sold",
    description: "The company you had shares in just got acquired.",
    amount: 6000,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_lawsuit",
    label: "Won a Lawsuit",
    description: "The court ruled in your favor. Settlement check incoming.",
    amount: 3500,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_scratchticket",
    label: "Scratch Ticket Win",
    description:
      "A dollar ticket from the gas station just changed everything.",
    amount: 3000,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_bookdeal",
    label: "Book Deal",
    description: "A publisher offered a shockingly generous advance.",
    amount: 3200,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_patentsold",
    label: "Patent Licensed",
    description: "A company wants to license your old side-project idea.",
    amount: 4500,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_viral",
    label: "Went Viral",
    description: "A random post blew up and the sponsorships followed.",
    amount: 2800,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_classaction",
    label: "Class Action Payout",
    description: "You forgot you even signed up for this settlement.",
    amount: 2200,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_casinowin",
    label: "Casino Hot Streak",
    description: "For once, the house didn't win.",
    amount: 4200,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_ipo",
    label: "IPO Windfall",
    description:
      "Your early employee stock options finally vested and paid off big.",
    amount: 7000,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_gameshow",
    label: "Won a Game Show",
    description: "You buzzed in first on the final round and swept the prize.",
    amount: 5500,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_treasurefound",
    label: "Found Treasure",
    description: "Renovating the attic turned up a box of old, valuable coins.",
    amount: 3800,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_bonuscheck",
    label: "Massive Year-End Bonus",
    description:
      "The company had a record quarter and it showed up in your check.",
    amount: 3000,
    wipeOut: false,
    jackpot: true,
  },
  {
    id: "gamble_royalties",
    label: "Royalty Check",
    description: "An old song you wrote just got used in a huge commercial.",
    amount: 4800,
    wipeOut: false,
    jackpot: true,
  },

  // ── Modest, in-between swings ───────────────────────────────────────
  {
    id: "gamble_friendgift",
    label: "Generous Friend",
    description: "A friend gave you $200, no strings attached.",
    amount: 200,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_plumber",
    label: "Plumber Bill",
    description: "The tap finally broke. The plumber wasn't cheap.",
    amount: -150,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldfurniture",
    label: "Sold Old Furniture",
    description: "That couch in storage just became someone else's problem.",
    amount: 100,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_parkingticket",
    label: "Parking Ticket",
    description: "You really should have read that sign.",
    amount: -75,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_foundcash",
    label: "Found Cash",
    description: "An old coat pocket had a nice surprise in it.",
    amount: 50,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_cartires",
    label: "New Tires",
    description: "The car needed new tires. All four of them.",
    amount: -300,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_sidegig",
    label: "Side Gig Payout",
    description: "That weekend gig finally paid out.",
    amount: 250,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_crackedscreen",
    label: "Cracked Screen",
    description: "The phone slipped. The repair bill didn't.",
    amount: -120,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_cashback",
    label: "Cashback Rewards",
    description: "Your card's rewards program finally paid off.",
    amount: 80,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_vetbill",
    label: "Vet Bill",
    description: "The dog is fine. Your wallet is not.",
    amount: -200,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_garagesale",
    label: "Garage Sale",
    description: "Turns out other people wanted your junk.",
    amount: 120,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_speedingticket",
    label: "Speeding Ticket",
    description: "The officer wasn't in a lenient mood today.",
    amount: -180,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_refereferral",
    label: "Referral Bonus",
    description: "A friend signed up using your code.",
    amount: 60,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenlaptop",
    label: "Broken Laptop",
    description: "Coffee and keyboards do not mix.",
    amount: -350,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldbike",
    label: "Sold Old Bike",
    description: "It was gathering dust anyway.",
    amount: 90,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_latefee",
    label: "Late Fee",
    description: "The bill slipped your mind by a week.",
    amount: -60,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_potluckwinnings",
    label: "Won the Office Pool",
    description: "Your bracket somehow held up.",
    amount: 150,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_dentalbill",
    label: "Dental Work",
    description: "That cavity wasn't going to fill itself for free.",
    amount: -220,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_freelancejob",
    label: "Freelance Job",
    description: "A quick weekend project came together nicely.",
    amount: 180,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_towedcar",
    label: "Car Got Towed",
    description: "Parked in the wrong spot at the worst time.",
    amount: -140,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_giftcard",
    label: "Unexpected Gift Card",
    description: "Someone remembered you like coffee. A lot.",
    amount: 40,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenwindow",
    label: "Broken Window",
    description: "A stray baseball found its target.",
    amount: -110,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_babysitting",
    label: "Babysitting Gig",
    description: "The neighbors needed a night out.",
    amount: 70,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_gymcancel",
    label: "Forgot to Cancel Gym",
    description: "Three months of unused membership, charged in full.",
    amount: -90,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldconcerttickets",
    label: "Resold Concert Tickets",
    description: "Couldn't make it, but someone else really wanted to.",
    amount: 130,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_applianceRepair",
    label: "Fridge Repair",
    description: "It made a weird noise for a week before finally quitting.",
    amount: -260,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wonraffle",
    label: "Won a Raffle",
    description: "Your ticket number actually got called this time.",
    amount: 100,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_overdraftfee",
    label: "Overdraft Fee",
    description:
      "You misjudged your balance by a few dollars, and it cost you.",
    amount: -35,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldskis",
    label: "Sold Old Ski Gear",
    description: "You haven't hit the slopes in years anyway.",
    amount: 140,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_jurydutypay",
    label: "Jury Duty Pay",
    description: "Not glamorous, but it's something.",
    amount: 45,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenumbrella",
    label: "Storm Damage",
    description: "The wind had other plans for your patio furniture.",
    amount: -95,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_petsitting",
    label: "Pet Sitting Gig",
    description: "Feeding a neighbor's cat for a week has its perks.",
    amount: 55,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_lostluggage",
    label: "Lost Luggage",
    description: "The airline's compensation didn't quite cover everything.",
    amount: -130,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldtextbooks",
    label: "Sold Old Textbooks",
    description: "Someone out there still needs Calculus II.",
    amount: 65,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenphonecharger",
    label: "Replaced Every Charger",
    description: "Every single one in the house died the same week.",
    amount: -40,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_streamingrefund",
    label: "Streaming Service Refund",
    description: "They double-charged you and actually fixed it.",
    amount: 30,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenglasses",
    label: "Broke Your Glasses",
    description: "Stepped on them getting out of bed. Classic.",
    amount: -170,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldvinyl",
    label: "Sold Old Vinyl Collection",
    description: "A collector paid more than you expected.",
    amount: 210,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_hoafine",
    label: "HOA Fine",
    description: "The lawn was apparently a quarter-inch too long.",
    amount: -85,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wonbingonight",
    label: "Won Bingo Night",
    description: "B-12 has never felt so sweet.",
    amount: 75,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenwatertheater",
    label: "Water Heater Died",
    description: "Cold showers until the replacement arrived.",
    amount: -280,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldcamera",
    label: "Sold Old Camera",
    description: "It was just collecting dust in a drawer.",
    amount: 160,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_libraryfine",
    label: "Library Fine",
    description: "That book has been overdue for months.",
    amount: -25,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldguitar",
    label: "Sold an Old Guitar",
    description: "You weren't really playing it anymore.",
    amount: 190,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenac",
    label: "AC Broke in Summer",
    description: "The repair guy was booked solid, and pricey.",
    amount: -240,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldshoes",
    label: "Resold Sneakers",
    description: "Turns out limited editions hold their value.",
    amount: 110,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_speedingcamera",
    label: "Speed Camera Ticket",
    description: "You didn't even see the flash.",
    amount: -95,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wonspellingbee",
    label: "Trivia Night Win",
    description: "Your team finally knew every answer.",
    amount: 85,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenfence",
    label: "Fence Repair",
    description: "The storm knocked over three panels.",
    amount: -160,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldjewelry",
    label: "Sold Old Jewelry",
    description: "It was just sitting in a drawer collecting dust.",
    amount: 230,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wificharge",
    label: "Unexpected Data Overage",
    description: "You blew through your phone plan's data cap.",
    amount: -50,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldkayak",
    label: "Sold Old Kayak",
    description: "It hadn't touched water in three summers.",
    amount: 175,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokendishwasher",
    label: "Dishwasher Repair",
    description: "Back to hand-washing for a while.",
    amount: -190,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wonchess",
    label: "Won a Chess Tournament",
    description: "Local club, small prize, big bragging rights.",
    amount: 95,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenmicrowave",
    label: "Microwave Died",
    description: "Sparks are never a good sign.",
    amount: -70,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldskateboard",
    label: "Sold Old Skateboard",
    description: "The wheels were still good, apparently.",
    amount: 45,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_finedlittering",
    label: "Littering Fine",
    description: "That receipt blew out of your hand at the worst time.",
    amount: -55,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldrecordplayer",
    label: "Sold a Record Player",
    description: "Vintage electronics fetch a decent price these days.",
    amount: 155,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenblinds",
    label: "Replaced All the Blinds",
    description: "They finally gave out after years of use.",
    amount: -80,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wonfantasyfootball",
    label: "Won Fantasy League",
    description: "Your sleeper pick carried the whole season.",
    amount: 200,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldgolfclubs",
    label: "Sold Old Golf Clubs",
    description: "You were never really that into golf.",
    amount: 165,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_finedjaywalking",
    label: "Jaywalking Fine",
    description: "The crosswalk was right there.",
    amount: -45,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldstamps",
    label: "Sold a Stamp Collection",
    description: "Grandpa's old hobby finally paid off.",
    amount: 145,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokentoilet",
    label: "Plumbing Emergency",
    description: "Middle of the night, worst possible timing.",
    amount: -210,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wonkaraoke",
    label: "Won Karaoke Night",
    description: "Nobody expected that falsetto.",
    amount: 65,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldtools",
    label: "Sold a Toolbox",
    description: "You never got around to that home project anyway.",
    amount: 125,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_finedlitteringpark",
    label: "No-Parking Fine",
    description: "The sign was small, but the fine wasn't.",
    amount: -65,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldpiano",
    label: "Sold an Old Keyboard",
    description: "It was mostly a coat rack these days.",
    amount: 185,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenlaundry",
    label: "Washing Machine Repair",
    description: "It started leaking mid-cycle.",
    amount: -230,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wontacoeating",
    label: "Won an Eating Contest",
    description: "Some skills you didn't know you had.",
    amount: 55,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldcomicbooks",
    label: "Sold Comic Book Collection",
    description: "Mint condition really does matter to collectors.",
    amount: 260,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_finedspeedwalking",
    label: "Toll Road Fine",
    description: "You forgot to load the transponder again.",
    amount: -30,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldlawnmower",
    label: "Sold Old Lawn Mower",
    description: "You hired a service instead. No regrets.",
    amount: 95,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokenoven",
    label: "Oven Repair",
    description: "Dinner plans changed rather abruptly.",
    amount: -175,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wonpoker",
    label: "Small Poker Win",
    description: "Nothing wild, just a solid night at the table.",
    amount: 140,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldtrampoline",
    label: "Sold a Trampoline",
    description: "The kids outgrew it years ago.",
    amount: 105,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_finedidling",
    label: "Idling Fine",
    description: "You didn't realize that was even a rule.",
    amount: -20,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldsnowblower",
    label: "Sold a Snowblower",
    description: "You moved somewhere warmer and don't need it anymore.",
    amount: 135,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_brokengarage",
    label: "Garage Door Repair",
    description: "The opener finally gave out after years of squeaking.",
    amount: -150,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_wondartsnight",
    label: "Won Darts Night",
    description: "Bullseye, three times in a row.",
    amount: 60,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_soldcanoe",
    label: "Sold an Old Canoe",
    description: "It hadn't seen a lake in years.",
    amount: 150,
    wipeOut: false,
    jackpot: false,
  },
  {
    id: "gamble_finednoinspection",
    label: "Expired Inspection Sticker",
    description: "You meant to get it renewed weeks ago.",
    amount: -60,
    wipeOut: false,
    jackpot: false,
  },
] as const;

export function gambleDef(cardId: string): GambleEvent | undefined {
  return GAMBLE_EVENTS.find((g) => g.id === cardId);
}
